<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

// One visitor chat (one page load); the id is a UUID generated by the browser.
#[Table(keyType: 'string', incrementing: false)]
#[Fillable(['id', 'ip_hash', 'user_agent', 'message_count'])]
class Conversation extends Model
{
    public function messages(): HasMany
    {
        return $this->hasMany(Message::class)->orderBy('id');
    }

    public function questions(): HasMany
    {
        return $this->hasMany(Question::class);
    }

    public function pendingQuestions(): HasMany
    {
        return $this->questions()->where('status', Question::PENDING);
    }
}
