#!/usr/bin/env bash
# Behind Cloudflare, nginx sees Cloudflare's addresses instead of visitors'. This trusts the
# CF-Connecting-IP header from Cloudflare's published ranges only, so rate limits and the chat log
# see the real visitor IP. Run as root once, and again if Cloudflare changes its ranges.
set -euo pipefail
OUT=/etc/nginx/conf.d/cloudflare-realip.conf
TMP=$(mktemp)
{
  echo "# generated by deploy/cloudflare-realip.sh on $(date +%F)"
  for v in 4 6; do
    curl -fsS "https://www.cloudflare.com/ips-v$v" | while read -r range; do
      [ -n "$range" ] && echo "set_real_ip_from $range;"
    done
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"
grep -q "set_real_ip_from" "$TMP"
install -m 644 "$TMP" "$OUT" && rm -f "$TMP"
nginx -t && systemctl reload nginx
echo "Trusting $(grep -c set_real_ip_from "$OUT") Cloudflare ranges"
